# Generated by Django 5.1 on 2025-09-11 09:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_price",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="home.region",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 11, 14, 26, 57, 482336)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="final_product_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="home.finish_product_category",
            ),
        ),
        migrations.AlterField(
            model_name="product_price",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="finl_product_price",
                to="home.final_product",
            ),
        ),
    ]
