# Generated by Django 5.1 on 2025-09-11 10:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_account_date_alter_product_price_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 11, 15, 42, 48, 913054)
            ),
        ),
        migrations.AlterField(
            model_name="final_product_price",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="home.customer",
            ),
        ),
    ]
