# Generated by Django 5.2.5 on 2025-09-12 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_account_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 15, 27, 25, 243632)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Accontant', 'Accontant'), ('Purchaser', 'Purchaser'), ('Office Boy', 'Office Boy'), ('Security Guard', 'Security Guard'), ('Driver', 'Driver'), ('Machine Operator', 'Machine Operator'), ('Foreman', 'Foreman'), ('Labour Incharge', 'Labour Incharge'), ('Fitter', 'Fitter'), ('Sweeper', 'Sweeper')], max_length=50),
        ),
    ]
