# Generated by Django 5.1 on 2025-09-11 11:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_account_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales_receipt",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="home.region",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 11, 16, 31, 41, 130472)
            ),
        ),
        migrations.AlterField(
            model_name="sales_receipt",
            name="customer_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="home.customer",
            ),
        ),
    ]
