# Generated by Django 5.2.5 on 2025-09-12 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_account_date_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 18, 56, 26, 674899)),
        ),
    ]
