# Generated by Django 5.2.5 on 2025-09-12 17:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_account_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 22, 50, 45, 30795)),
        ),
        migrations.CreateModel(
            name='Final_Product_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Final_Product_Note_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('final_product_note', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.final_product_note')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.final_product')),
            ],
        ),
        migrations.AddField(
            model_name='final_product_note',
            name='products',
            field=models.ManyToManyField(through='home.Final_Product_Note_Product', to='home.final_product'),
        ),
    ]
