# Generated by Django 5.1 on 2025-09-12 20:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_account_date_final_product_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 13, 1, 16, 49, 272479)
            ),
        ),
        migrations.AlterField(
            model_name="final_product",
            name="product_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sales_receipt",
            name="products",
            field=models.ManyToManyField(
                through="home.Sales_Receipt_Product", to="home.final_product"
            ),
        ),
        migrations.AlterField(
            model_name="sales_receipt_product",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="home.final_product"
            ),
        ),
    ]
