# Generated by Django 5.1 on 2025-09-13 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_account_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 13, 12, 51, 8, 354266)
            ),
        ),
        migrations.AlterField(
            model_name="final_product",
            name="purchase",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="final_product",
            name="sale_rate",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
