# Generated by Django 5.1 on 2025-09-14 10:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_account_date_alter_final_product_purchase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 14, 15, 12, 44, 526335)
            ),
        ),
        migrations.AlterField(
            model_name="final_product_price",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="final_product_price",
                to="home.final_product",
            ),
        ),
        migrations.AlterField(
            model_name="product_price",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="product_price",
                to="home.product",
            ),
        ),
        migrations.AlterField(
            model_name="sales_receipt_product",
            name="salereceipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sales_receipt_products",
                to="home.sales_receipt",
            ),
        ),
    ]
