# Generated by Django 5.1 on 2025-09-14 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_account_date_alter_final_product_price_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 14, 15, 20, 43, 580680)
            ),
        ),
    ]
