# Generated by Django 5.1 on 2025-09-14 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_account_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="final_product_price",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 14, 17, 32, 18, 604590)
            ),
        ),
    ]
