# Generated by Django 5.1 on 2025-09-14 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_final_product_price_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 14, 17, 39, 9, 160926)
            ),
        ),
    ]
