# Generated by Django 5.1 on 2025-09-15 09:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_account_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="final_product_price",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="final_product_price",
            name="region",
        ),
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 15, 14, 26, 59, 158947)
            ),
        ),
        migrations.AddField(
            model_name="final_product_price",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="final_pro_price",
                to="home.price_list",
            ),
        ),
    ]
