# Generated by Django 5.1 on 2025-09-15 10:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_price_list_remove_final_product_price_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 15, 15, 24, 11, 169267)
            ),
        ),
        migrations.AlterField(
            model_name="final_product_price",
            name="price_list",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="final_pro_price",
                to="home.price_list",
            ),
            preserve_default=False,
        ),
    ]
