# Generated by Django 5.1 on 2025-09-16 08:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_account_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 16, 13, 55, 2, 816125)
            ),
        ),
        migrations.CreateModel(
            name="Price_list_note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price_List_Note_products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                (
                    "price_list_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.price_list_note",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.final_product",
                    ),
                ),
                (
                    "ptice_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.price_list",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="price_list_note",
            name="price_list",
            field=models.ManyToManyField(
                through="home.Price_List_Note_products", to="home.price_list"
            ),
        ),
    ]
