# Generated by Django 5.1 on 2025-09-16 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_account_date_price_list_note_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="price_list_note_products",
            old_name="ptice_list",
            new_name="price_list",
        ),
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 16, 13, 59, 31, 267228)
            ),
        ),
    ]
