# Generated by Django 5.1 on 2025-09-16 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_rename_ptice_list_price_list_note_products_price_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 16, 17, 33, 37, 361791)
            ),
        ),
        migrations.AlterField(
            model_name="price_list_note",
            name="price_list",
            field=models.ManyToManyField(
                through="home.Price_List_Note_Products", to="home.price_list"
            ),
        ),
    ]
