# Generated by Django 5.1 on 2025-09-16 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_account_date_alter_price_list_note_price_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 16, 18, 34, 23, 146240)
            ),
        ),
    ]
