# Generated by Django 5.1 on 2025-09-17 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_account_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 17, 18, 0, 58, 631523)
            ),
        ),
    ]
