# Generated by Django 5.1 on 2025-09-17 13:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_alter_account_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="price_list_note",
            name="products",
            field=models.ManyToManyField(
                through="home.Price_List_Note_Products", to="home.final_product"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 17, 18, 39, 55, 43295)
            ),
        ),
        migrations.RemoveField(
            model_name="price_list_note",
            name="price_list",
        ),
        migrations.AddField(
            model_name="price_list_note",
            name="price_list",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.price_list",
            ),
            preserve_default=False,
        ),
    ]
