# Generated by Django 5.2.5 on 2025-09-18 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_price_list_note_products_alter_account_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 18, 5, 12, 56, 759622)),
        ),
    ]
