# Generated by Django 5.2.5 on 2025-09-18 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_account_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 18, 5, 36, 30, 692374)),
        ),
        migrations.AlterUniqueTogether(
            name='final_product_note_product',
            unique_together={('final_product_note', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='price_list_note_products',
            unique_together={('price_list_note', 'product')},
        ),
    ]
