# Generated by Django 5.2.5 on 2025-09-18 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_account_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 18, 6, 9, 28, 700167)),
        ),
        migrations.AlterUniqueTogether(
            name='price_list_note_products',
            unique_together={('price_list', 'product', 'price')},
        ),
    ]
