# Generated by Django 5.1 on 2025-09-18 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_alter_account_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 18, 9, 32, 23, 859862)
            ),
        ),
    ]
